apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
stringData:
  config.json: |
    {
      "auths": {
        "quay.io": {
          "auth": "<auth>",
          "email": "<email>"
        }
      }
    }