apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: wind-turbine-apps
  namespace: openshift-gitops 
spec:
  generators: 
  - git:
      repoURL: "https://github.com/sa-mw-dach/quinoa-wind-turbine-manifests"
      revision: main
      files:
      - path: "stages/**/config.json"
  # - list:
  #     elements:
  #     - cluster: dev
  #       url: https://kubernetes.default.svc
  #       namespace: gitops-demo-dev
  #       imageTag: "latest"
  #       followChangesForBranch: "main"
  #     - cluster: stage
  #       url: https://kubernetes.default.svc
  #       namespace: gitops-demo-stage
  #       imageTag: "Release-1.0.2"
  #       followChangesForBranch: "Release-1.0" # build when startsWith
  #     - cluster: prod
  #       url: https://kubernetes.default.svc
  #       namespace: gitops-demo-prod
  #       imageTag: "Release-1.0.0"
  #       followChangesForBranch: "" # -> empty means don't follow
  template:
    metadata:
      name: 'wind-turbine-{{stage}}-app'
    spec:
      project: default 
      source:
        repoURL: "https://github.com/sa-mw-dach/quinoa-wind-turbine-manifests"
        path: helm
        helm:
          # valueFiles: 
          # - values.{{cluster}}.yaml
          parameters:
          - name: repoUrl
            value: 'https://github.com/sa-mw-dach/quinoa-wind-turbine-manifests'
          - name: applicationGitUrl
            value: 'https://github.com/sa-mw-dach/quinoa-wind-turbine.git'
          - name: image
            value: 'quay.io/sbergste/quinoa-wind-turbine'
          - name: imageTag
            value: '{{imageTag}}'
          - name: imageDigest
            value: '{{imageDigest}}'
          - name: followChangesForBranch
            value: '{{followChangesForBranch}}'
          - name: stage
            value: '{{stage}}'
          - name: disableSecretsDeployment
            value: 'true'
          - name: replicas
            value: '{{replicas}}'
      destination:
        server: '{{url}}' 
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image